import { defineNoteConfig } from "vuepress-theme-plume";

export const documentationNote = defineNoteConfig({
	dir: "documentation",
	link: "/documentation",
	sidebar: [
		{
			text: "Welcome",
			link: "/documentation/intro.md",
		},

		{
			text: "Start",
			collapsed: true,
			prefix: "/documentation/Start/",
			items: "auto",
		},
		{
			text: "Setup",
			collapsed: true,
			prefix: "/documentation/Setup/",
			items: "auto",
		},
		{
			text: "Console",
			collapsed: true,
			prefix: "/documentation/Console/",
			items: "auto",
		},
		{
			text: "Datasource",
			collapsed: true,
			prefix: "/documentation/Datasource/",
			items: "auto",
		},
		{
			text: "Model",
			collapsed: true,
			prefix: "/documentation/Model/",
			items: [
				{ text: "Analysis Model Overview", link: "/documentation/Model/Analysis-Model-Overview/" },
				{ text: "Managing Analysis Models", link: "/documentation/Model/Managing-Analysis-Models/" },
				{ text: "Creating an Analysis Model", link: "/documentation/Model/Creating-an-Analysis-Model/" },
				{ text: "Working with Tables and the Canvas", link: "/documentation/Model/Working-with-Tables-and-the-Canvas/" },
				{ text: "Creating SQL Views", link: "/documentation/Model/Creating-SQL-Views/" },
				{ text: "Establishing Table Relationships", link: "/documentation/Model/Establishing-Table-Relationships/" },
				{ text: "Advanced Relationship Modeling", link: "/documentation/Model/Advanced-Relationship-Modeling/" },
				{ text: "Tidy Model into a Star Schema", link: "/documentation/Model/Tidy-Model-into-a-Star-Schema/" },
				{ text: "Creating Hierarchies", link: "/documentation/Model/Creating-Hierarchy/" },
				{ text: "Time Semantics and Default Time Settings", link: "/documentation/Model/Time-Dimensions-and-Time-Intelligence/" },
				{ text: "Calculated Columns", link: "/documentation/Model/Calculated-Field/" },
				{ text: "Measures and Calculated Measures", link: "/documentation/Model/Measures-and-Calculated-Measures/" },
				{ text: "Units and Display Scale", link: "/documentation/Model/Units-and-Display-Scale/" },
				{ text: "Use Aggregation Tables", link: "/documentation/Model/Use-Aggregation-Tables/" },
				{ text: "Business Semantics for AI", link: "/documentation/Model/Business-Semantics-for-AI/" },
				{ text: "Model Diagnostics", link: "/documentation/Model/Model-Diagnostics/" },
			],
		},
		{
			text: "Metrics Library",
			collapsed: true,
			prefix: "/documentation/Metrics Library/",
			items: "auto",
		},
		{
			text: "Visualization",
			collapsed: true,
			prefix: "/documentation/Visualization/",
			items: [
				{
					text: "Page Settings",
					link: "/documentation/Visualization/08 报表页的大小和显示方式.md",
				},
				{
					text: "Adding Components",
					link: "/documentation/Visualization/10 添加图表.md",
				},
				{
					text: "Charts",
					collapsed: true,
					prefix: "/documentation/Visualization/Chart/",
					items: "auto",
				},
				{
					text: "Tables",
					collapsed: true,
					prefix: "/documentation/Visualization/Table/",
					items: "auto",
				},
				{
					text: "Maps",
					collapsed: true,
					prefix: "/documentation/Visualization/Map/",
					items: "auto",
				},
				{
					text: "Filters",
					collapsed: true,
					prefix: "/documentation/Visualization/Filters/",
					items: "auto",
				},
				{
					text: "Assists",
					collapsed: true,
					prefix: "/documentation/Visualization/Assists/",
					items: "auto",
				},
				{
					text: "Tabs",
					link: "/documentation/Visualization/26 制作多标签页面.md",
				},
				{
					text: "Formatting",
					collapsed: true,
					items: [
						{ text: "Display Units and Decimal Places", link: "/documentation/Visualization/30 Display Units and Decimal Places.md" },
						{ text: "Colors and Color Schemes", link: "/documentation/Visualization/32 Colors and Color Schemes.md" },
						{ text: "Conditional Formatting", link: "/documentation/Visualization/110 条件颜色设置.md" },
						{ text: "Tooltips", link: "/documentation/Visualization/40_图表组件的工具提示.md" },
						{ text: "Legends", link: "/documentation/Visualization/42 Legends.md" },
						{ text: "X Axis Type", link: "/documentation/Visualization/81 X 轴类型设置：连续和类别.md" },
						{ text: "Empty Data and Error Messages", link: "/documentation/Visualization/44 Empty Data and Error Messages.md" },
					],
				},
				{
					text: "Mobile Layout View",
					link: "/documentation/Visualization/12 手机布局视图.md",
				},
				{
					text: "Export",
					link: "/documentation/Visualization/130 导出.md",
				},
			],
		},
		{
			text: "Analysis",
			collapsed: true,
			prefix: "/documentation/Analysis/",
			items: "auto",
		},
		{
			text: "AI Agent",
			collapsed: true,
			prefix: "/documentation/AI-Agent/",
			items: "auto",
		},		
		{
			text: "Embedded",
			collapsed: true,
			prefix: "/documentation/Embedded/",
			items: "auto",
		},
		{
			text: "Multi-tenancy",
			collapsed: true,
			prefix: "/documentation/Multi-tenancy/",
			items: "auto",
		},
		{
			text: "Tools",
			collapsed: true,
			prefix: "/documentation/Tools/",
			items: "auto",
		},
		{
			text: "System",
			collapsed: true,
			prefix: "/documentation/System/",
			items: "auto",
		},
		{
			text: "Advanced",
			collapsed: true,
			prefix: "/documentation/Advanced/",
			items: "auto",
		},
		{
			text: "Best Practices",
			collapsed: true,
			prefix: "/documentation/Best/",
			items: "auto",
		},
		{
			text: "Security & Compliance",
			collapsed: true,
			prefix: "/documentation/Security/",
			items: "auto",
		},		
	],
});
